import createClient from 'openapi-fetch';
import type { paths } from './schema'; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: 'https://musicfun.it-incubator.app/api/1.0/',
  headers: {
    'api-key': 'be263d02-b695-4665-9327-aae843a701d1',
  },
});
